### ISSUE TITLE
Does not work with aframe 0.3.2

### ISSUE THREAD

**Issue by rondagdag** [mayognaise/aframe-html-shader#6]
I am having trouble using this module with aframe 0.3.2
It will not display the html canvas, just getting blank page.

**Comment by Alucelx** [comment]
@rondagdag 

I just fixed it myself yestoday.
Find the code at line 358 in index.js, the code like this:
````javascript
/* change size */
const { width, height } = this.el.getObject3D('mesh').geometry.parameters;
````

change that line to this code
````javascript
const { width, height } = this.el.getObject3D('mesh').geometry.metadata.parameters;
````

then  run command: npm run dist
or npm run build

enjoy it~

**Comment by sachinaaglave** [comment]
@Alucelx

(aframe 0.3.0) after applying changes as you mentioned. When I open examples/basic/index.html in google chrome, I am not getting any error in console but text html is not rendered. 

Thanks

**Comment by Alucelx** [comment]
@sachinaglave 

there's two reasons:
1. default position of camera has changed in aframe@^0.3.0.
2. aframe cannot find the text target while run text shader

so, we do two small change with demo html doc to fix it.
1. add camera definition code into &lt;a-scene&gt;, like this:
````javascript
<a-entity position="0 1.8 4" camera wasd-controls look-controls></a-entity>
````
2. move "#htmlTarget" element to the top of &lt;body&gt;, just before &lt;a-scene&gt; element.

after these, you can see the demo.

ps:
you must do "npm run dist" command before "npm run build", or you can't get the newest change with the source code in "example/build.js"

i hope i am not too late, enjoy it.

**Comment by Alucelx** [comment]
@sachinaglave 
i forgot one change.

find the class ".buttons" in "example/common.css",  add one line "top: 0;" into it.

then "toggle dom" and "toggle debug" action will shown on the screen.

**Comment by sachinaaglave** [comment]
@Alucelx 
Thank its working now.

**Comment by ngokevin** [comment]
Updated
